before_script:
  - date
  - uname -a
  - printenv | sort

# python:
#   image: gpdowning/python
#   script:
#     - ls -al
#     - cat makefile
#     - make versions
#     - make run
#     - make test
#     - make tests
#     - make check

stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run postman.json

frontend_tests:
  stage: test
  image: 
  script:
    - cd frontend
    - npm run test