before_script:
  - date
  - uname -a
  - printenv | sort

stages:
  - test
 

python:
  image: 
    name: gpdowning/python
    entrypoint: [""]
  script:
    - cd backend
    - pip install -r requirements.txt
    - python test.py

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run postman.json
    
frontend_tests:
  stage: test
  image: 
  script:
    - cd frontend
    - npm install
    - npm run test