before_script:
    - date
    - uname -a
    - printenv | sort

# python:
#     image: gpdowning/python
#     script:
#     - ls -al
#     - cat makefile
#     - make versions
#     - make run
#     - make test
#     - make tests
#     - make check
