before_script:
  - date
  - uname -a
  - printenv | sort

python:
  image: 
    name: gpdowning/python
    entrypoint: [""]
  script:
    - cd backend
    - python test.py

node:
  image: joewallery/node
  script:
    - ls -al
#   - cat makefile
#   - make versions
#   - make test

stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run postman.json
